### ISSUE TITLE
java.lang.NullPointerException at clodiuno.firmata$fn__129.invoke(firmata.clj:95)

### ISSUE THREAD

**Issue by Gonzih** [nakkaya/clodiuno#2]
Hi, clodiuno is nice, thanks for that! :D
I'm stuck with exception. Here my code:

``` clojure
(ns clojure-arduino.core
  (:use :reload-all clodiuno.core)
  (:use :reload-all clodiuno.firmata))

(System/setProperty "gnu.io.rxtx.SerialPorts" "/dev/ttyACM0")

(defn -main []
  (let [board (arduino :firmata "/dev/ttyACM0")]
    (Thread/sleep 5000)
    (pin-mode board 12 OUTPUT)
    (digital-write board 12 HIGH)
    (close board)))

```

Here is my exception message:

```
Exception in thread "main" java.lang.NullPointerException (NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5440)
        at clojure.lang.Compiler.eval(Compiler.java:5415)
        at clojure.lang.Compiler.eval(Compiler.java:5391)
        at clojure.core$eval.invoke(core.clj:2382)
        at clojure.main$eval_opt.invoke(main.clj:235)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$null_opt.invoke(main.clj:279)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:422)
        at clojure.lang.Var.invoke(Var.java:369)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
        at clodiuno.firmata$fn__129.invoke(firmata.clj:95)
        at clojure.lang.MultiFn.invoke(MultiFn.java:171)
        at clojure_arduino.core$_main.invoke(core.clj:12)
        at clojure.lang.Var.invoke(Var.java:361)
        at user$eval38.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        ... 12 more


```

As I can see `firmata.clj:95` tries to access `:digital-out` from conn map that is nil.

Thanks for help
Max

**Comment by ardumont** [comment]
Hi,

I just add the same problem and i work around it by modifying the content of file firmata.clj at the same spot that you targeted.

This is in the other issue i opened https://github.com/nakkaya/clodiuno/issues/1

I'm going for the pull request i hope nakkaya will merge.

**Comment by Gonzih** [comment]
@ardumont Oh, that's cool. So I will close my issue now. Thanks for info!
